# utilisateur =  @Route("/utilisateur", name="utilisateur")
# register = @Route("/register", name="app_register") --> OK
# abonnement = @Route("/abonnement", name="abonnement")
# Authentification = @Route("/login", name="app_login") --> OK
# Cours = @Route("/cours", name="cours")
# matiere = @Route("/matiere", name="matiere")
# Mode de paiement @Route("/mode/de/paiement", name="mode_de_paiement")
# Niveau = @Route("/niveau", name="niveau")

# ------- page d'acceuil ---------
acceuil:
  path: /acceuil
  controller: App\Controller\AcceuilController::acceuil

#---------- profil -----------
profil_update:
  path: /profil/update
  controller: App\Controller\ProfilController::update


profil_delete:
  path: /profil/delete/{id}
  controller: App\Controller\ProfilController::delete
  requirements :
    id: \d+  

#--------- Page Niveau--------
   
niveau_create:
  path: /admin/niveau/creer
  controller: App\Controller\NiveauController::create

niveau_supprimer:
  path: /admin/niveau/supprimer/{id}
  controller: App\Controller\NiveauController::delete
  requirements :
    id: \d+   

niveau_all:
  path: /admin/niveau/all
  controller: App\Controller\NiveauController::niveauAll

niveau_show:
    path: /admin/niveau/show/{id}
    controller: App\Controller\NiveauController::niveauShow
    requirements :
      id: \d+    

#--------- Page Mode de paiement--------
modedepaiement_create:
  path: /admin/modedepaiement/creer
  controller: App\Controller\ModeDePaiementController::create

modedepaiement_supprimer:
    path: /admin/modedepaiement/supprimer/{id}
    controller: App\Controller\ModeDePaiementController::delete
    requirements :
      id: \d+   

modedepaiement_all:
  path: /admin/modedepaiement/all
  controller: App\Controller\ModeDePaiementController::modeDePaiementAll

modedepaiement_show:
    path: /admin/modedepaiement/show/{id}
    controller: App\Controller\ModeDePaiementController::modeDePaiementShow
    requirements :
        id: \d+    

        
#--------- matiere--------   


matiere_create:
  path: /admin/matiere/creer
  controller: App\Controller\MatiereController::create

matiere_supprimer:
    path: /admin/matiere/supprimer/{id}
    controller: App\Controller\MatiereController::delete
    requirements :
      id: \d+   

matiere_all:
  path: /admin/matiere/all
  controller: App\Controller\MatiereController::matiereAll

matiere_show:
    path: /admin/matiere/show/{id}
    controller: App\Controller\MatiereController::matiereShow
    requirements :
      id: \d+    


#--------- abonnement --------   


abonnement_create:
  path: /admin/abonnement/creer
  controller: App\Controller\AbonnementController::create

abonnement_supprimer:
    path: /admin/abonnement/supprimer/{id}
    controller: App\Controller\AbonnementController::delete
    requirements :
      id: \d+   

abonnement_all:
  path: /admin/abonnement/all
  controller: App\Controller\AbonnementController::abonnementAll

abonnement_show:
    path: /admin/abonnement/show/{id}
    controller: App\Controller\AbonnementController::abonnementShow
    requirements :
      id: \d+    
